repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
  - repo: local
    hooks:
      - id: flake8
        name: Flake8 linting
        description: Runs flake8 on GitHub's source code to look for lint
        entry: poetry run flake8
        language: system
        types:
          - python
        require_serial: true
