[tool.poetry]
name = "octocat"
version = "0.1.0"
description = "A moderation and utility bot for GitHub Discord"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.5.3"
"discord.py" = {url = "https://github.com/Rapptz/discord.py/archive/master.zip"}
pydantic = {extras = ["dotenv"], version = "^1.8.2"}

[tool.poetry.dev-dependencies]
taskipy = "^1.8.1"

[tool.taskipy.tasks]
start = "python -m arthur"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
